_target_: src.models.ImageClassifierModule

dataset: "brats"
num_timesteps: 1000

optimizer:
  _target_: torch.optim.AdamW
  _partial_: true
  lr: 1e-4
  weight_decay: 1e-6

scheduler:
  _target_: torch.optim.lr_scheduler.CosineAnnealingLR
  _partial_: true
  T_max: 100
  eta_min: 1e-6

classifier_path: ${paths.root_dir}/src/ckpt_s256/classifier/image_classifier_brats2020.pth