defaults:
  - _self_
  - /data: brats2020.yaml
  - /model: diffusion/latent_diffusion_module.yaml 
  - /paths: default.yaml

task_name: "sample_ldm"
tags: ["inference", "sampling"]
seed: 12345

data:
  batch_size: 1
  num_workers: 4
  image_size: 256

classifier:
  use_classifier: true
  path: /home/tqlong/qtung/gen-model-boilerplate/src/ckpt_s256/classifier/classifier_ldm64_1000step.pth
  scale: 100.0 # Scale for classifier guidance (s)
  use_label: true  

sampling:
  num_samples: 25
  # save_dir: /home/tqlong/qtung/gen-model-boilerplate/results/ldm_s256/brats2020_z64_no_classifier  # No classifier
  save_dir: /home/tqlong/qtung/gen-model-boilerplate/results/inference_comparison_v2
  noise_level: 200  # L
  skip_normal: true 